from bbs import *

def testing():
    clean_reset()
    connect("kathi", True)
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    post_msg("vscode", "reinstall")
    post_msg("headache", "hello")
    post_msg("vscode headache number 2", "config error")
    find_print_msg(1)
    find_print_msg(2)     
    find_print_msg(3)
    remove_msg(1)
    remove_msg(103)
    post_msg("vscode headache number 2", "config error")
    print(print_summary())


def testing2():
    clean_reset()
    connect("kathi", True)
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    soft_disconnect()  
    connect("nick", False)
    print_summary("homework")
    find_print_msg(1)
    post_msg("handout followup", "yep, ready to go")
    remove_msg(1)
    print_summary()
    disconnect()

def testing3():
    clean_reset()
    connect("kathi", True)
    post_msg("post homework?", "is the handout ready?")
    post_msg("vscode headache", "reinstall to fix the config error")
    soft_disconnect()  
    connect("nick", False)
    print_summary("homework")
    find_print_msg(1)
    post_msg("handout followup", "yep, ready to go")
    remove_msg(1)
    print_summary("handout")
    remove_msg(2)
    disconnect()
